name: Build Docker Image

on:
  push:
    branches:
      - 'master'
      - 'main'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
          - { tag: "prefectinspect", dockerfile: "test/prefectbash/Dockerfile"}

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR (GitHub Packages)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: "ghcr.io/bnosac/blackbar-${{ matrix.config.tag }}:latest"
          file: ${{ matrix.config.dockerfile }}
