name: Build Docker Image

on:
  push:
    branches:
      - 'master'
      - 'main'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
          - { tag: "prefectinspect", dockerfile: "test/prefectinspect/Dockerfile", context: "test/prefectinspect"}
          - { tag: "base", dockerfile: "anonymization/Dockerfile", context: "anonymization"}
          - { tag: "apps", dockerfile: "apps/Dockerfile", context: "apps"}
          #- { tag: "prefectexample", dockerfile: "test/prefectexample/Dockerfile", context: "test/prefectexample"}

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR (GitHub Packages)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to datatailor
        uses: docker/login-action@v2
        with:
          registry: registry.datatailor.be
          username: ${{ secrets.DATATAILOR_REGISTRY_USER }}
          password: ${{ secrets.DATATAILOR_REGISTRY_PWD }}

      - name: Build and push ghcr.io
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.config.context }}
          push: true
          tags: "ghcr.io/bnosac/blackbar-${{ matrix.config.tag }}:latest"            
          file: ${{ matrix.config.dockerfile }}

      - name: Build and push Dockerhub
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.config.context }}
          push: true
          tags: "bnosac/blackbar-${{ matrix.config.tag }}:latest"            
          file: ${{ matrix.config.dockerfile }}

      - name: Build and push registry.datatailor.be
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.config.context }}
          push: true
          tags: "registry.datatailor.be/blackbar-${{ matrix.config.tag }}:latest"            
          file: ${{ matrix.config.dockerfile }}
